Repository googleapis/java-area120-tables, pull requests merged in 2020-09, with the labels that each got.

#7 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#11 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#14 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#25 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#31 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#32 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
