Repository googleapis/java-area120-tables, pull requests merged in 2020-10, with the labels that each got.

#34 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#42 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#44 chore: regenerate common templates
  .github/workflows/approve-readme.yaml
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#45 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#54 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#55 chore: regenerate common templates
  .github/snippet-bot.yml
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#57 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#58 Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: full

#59 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .kokoro/build.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: cla: yes, context: full

#47 chore: corrects api_id
  .repo-metadata.json
Labels: cla: yes

#61 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#63 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full
