Repository googleapis/java-area120-tables, pull requests merged in 2021-02, with the labels that each got.

#109 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: cla: yes, context: partial

#110 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#111 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#113 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#114 docs: generate sample code in the Java microgenerator
  google-area120-tables/src/main/java/com/google/area120/tables/v1alpha/TablesServiceClient.java
  google-area120-tables/src/main/java/com/google/area120/tables/v1alpha/package-info.java
  synth.metadata
Labels: automerge, cla: yes, context: full, samples

#116 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#71 chore: give area120-tables push access
  .github/sync-repo-settings.yaml
Labels: cla: yes

#123 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#128 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
