Repository googleapis/java-area120-tables, pull requests merged in 2021-05, with the labels that each got.

#161 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: area120tables, automerge, cla: yes, context: none

#162 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: area120tables, automerge, cla: yes

#163 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: area120tables, automerge, cla: yes, context: full

#165 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: area120tables, automerge, cla: yes, context: full

#166 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: area120tables, automerge, cla: yes, context: full

#170 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: area120tables, automerge, cla: yes, context: full

#175 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: area120tables, automerge, cla: yes
